spring:
  application:
    name: scraper
  datasource:
    url: jdbc:postgresql://localhost:5436/scraper
    username: user   # ???????? ?? ??? ???????????? ????? ??
    password: user   # ???????? ?? ?????? ????? ??
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # ?????????????? ????????/?????????? ?????. ???????? ?? "none" ? ??????????.
    show-sql: true       # ???????? ??????????? SQL-???????? ? ???????
    properties:
      hibernate:
        format_sql: true # ????????????? ????? SQL-???????? ??? ???????????????

server:
  port: 8090            # ????, ?? ??????? ????? ???????? ??????????
  error:
    include-message: always # ????????? ????????? ?? ??????? ? ???????
