spring:
  application:
    name: scraper
  datasource:
    url: jdbc:postgresql://localhost:5436/scraper
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: elastic_password

server:
  port: 8090
  error:
    include-message: always
